# Generated by Django 5.1.1 on 2024-12-05 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diseases", "0002_pneumoniasegmentation_delete_pneumonia"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="pneumoniasegmentation",
            name="segmented_image",
            field=models.ImageField(upload_to="segmented/"),
        ),
        migrations.CreateModel(
            name="Autism",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="autistic/")),
                (
                    "predicted_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autism",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
