# Generated by Django 5.1.1 on 2024-12-07 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diseases", "0005_nutritionprediction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CovidPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Fever", models.BooleanField()),
                ("Tiredness", models.BooleanField()),
                ("Dry_Cough", models.BooleanField()),
                ("Difficulty_in_Breathing", models.BooleanField()),
                ("Sore_Throat", models.BooleanField()),
                ("None_Sympton", models.BooleanField()),
                ("Pains", models.BooleanField()),
                ("Nasal_Congestion", models.BooleanField()),
                ("Runny_Nose", models.BooleanField()),
                ("Diarrhea", models.BooleanField()),
                ("None_Experiencing", models.BooleanField()),
                ("Age_0_9", models.BooleanField()),
                ("Age_10_19", models.BooleanField()),
                ("Age_20_24", models.BooleanField()),
                ("Age_25_59", models.BooleanField()),
                ("Age_60_plus", models.BooleanField()),
                ("Gender_Female", models.BooleanField()),
                ("Gender_Male", models.BooleanField()),
                ("Gender_Transgender", models.BooleanField()),
                ("Severity_Mild", models.BooleanField()),
                ("Severity_Moderate", models.BooleanField()),
                ("Severity_None", models.BooleanField()),
                ("Contact_Dont_Know", models.BooleanField()),
                ("Contact_No", models.BooleanField()),
                ("Contact_Yes", models.BooleanField()),
                (
                    "predicted_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("llm_details", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="covid",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
