# Generated by Django 5.1.1 on 2024-12-07 05:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diseases", "0006_covidprediction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="covidprediction",
            name="llm_details",
        ),
    ]
