# Generated by Django 5.1.1 on 2024-12-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diseases", "0007_remove_covidprediction_llm_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="covidprediction",
            name="predicted_text",
            field=models.TextField(),
        ),
    ]
