# Generated by Django 5.1.1 on 2024-12-07 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diseases", "0009_alter_covidprediction_age_0_9_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="covidprediction",
            old_name="None_Sympton",
            new_name="None_Symptom",
        ),
    ]
