# Generated by Django 5.1.1 on 2024-12-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diseases", "0010_rename_none_sympton_covidprediction_none_symptom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="covidprediction",
            name="predicted_text",
            field=models.CharField(max_length=20),
        ),
    ]
