# Generated by Django 5.1.1 on 2024-12-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diseases", "0011_alter_covidprediction_predicted_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="covidprediction",
            name="predicted_text",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
