# Generated by Django 5.1.1 on 2024-12-08 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diseases", "0012_alter_covidprediction_predicted_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HepatitisPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.CharField(max_length=10)),
                ("sex", models.CharField(max_length=10)),
                ("steroid", models.CharField(max_length=10)),
                ("antivirals", models.CharField(max_length=10)),
                ("fatigue", models.CharField(max_length=10)),
                ("malaise", models.CharField(max_length=10)),
                ("anorexia", models.CharField(max_length=10)),
                ("liver_big", models.CharField(max_length=10)),
                ("liver_firm", models.CharField(max_length=10)),
                ("spleen_palpable", models.CharField(max_length=10)),
                ("spiders", models.CharField(max_length=10)),
                ("ascites", models.CharField(max_length=10)),
                ("varices", models.CharField(max_length=10)),
                ("bilirubin", models.CharField(max_length=10)),
                ("alk_phosphate", models.CharField(max_length=10)),
                ("sgot", models.CharField(max_length=10)),
                ("albumin", models.CharField(max_length=10)),
                ("protime", models.CharField(max_length=10)),
                ("histology", models.CharField(max_length=10)),
                (
                    "predicted_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hepatitis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
