# Generated by Django 5.1.1 on 2024-12-10 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diseases", "0014_strokeprediction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiabetesPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Pregnancies", models.CharField(max_length=50)),
                ("Glucose", models.CharField(max_length=10)),
                ("BloodPressure", models.CharField(max_length=10)),
                ("SkinThickness", models.CharField(max_length=10)),
                ("Insulin", models.CharField(max_length=50)),
                ("BMI", models.CharField(max_length=100)),
                ("DiabetesPedigreeFunction", models.CharField(max_length=50)),
                ("Age", models.CharField(max_length=20)),
                (
                    "predicted_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diabetes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KidneyDiseasePrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.CharField(max_length=50)),
                ("blood_pressure", models.CharField(max_length=50)),
                ("specific_gravity", models.CharField(max_length=10)),
                ("albumin", models.CharField(max_length=10)),
                ("sugar", models.CharField(max_length=10)),
                ("red_blood_cells", models.CharField(max_length=50)),
                ("pus_cell", models.CharField(max_length=100)),
                ("pus_cell_clumps", models.CharField(max_length=50)),
                ("bacteria", models.CharField(max_length=20)),
                ("blood_glucose_random", models.CharField(max_length=20)),
                ("blood_urea", models.CharField(max_length=20)),
                ("serum_creatinine", models.CharField(max_length=20)),
                ("sodium", models.CharField(max_length=20)),
                ("potassium", models.CharField(max_length=20)),
                ("haemoglobin", models.CharField(max_length=20)),
                ("packed_cell_volume", models.CharField(max_length=20)),
                ("white_blood_cell_count", models.CharField(max_length=20)),
                ("red_blood_cell_count", models.CharField(max_length=20)),
                ("hypertension", models.CharField(max_length=20)),
                ("diabetes_mellitus", models.CharField(max_length=20)),
                ("coronary_artery_disease", models.CharField(max_length=20)),
                ("appetite", models.CharField(max_length=20)),
                ("peda_edema", models.CharField(max_length=10)),
                ("aanemia", models.CharField(max_length=50)),
                (
                    "predicted_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kidney_disease",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
