# Generated by Django 5.1.1 on 2025-06-08 05:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diseases", "0015_diabetesprediction_kidneydiseaseprediction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="braintumor",
            name="user",
        ),
        migrations.RemoveField(
            model_name="covidprediction",
            name="user",
        ),
        migrations.RemoveField(
            model_name="diabetesprediction",
            name="user",
        ),
        migrations.RemoveField(
            model_name="hepatitisprediction",
            name="user",
        ),
        migrations.RemoveField(
            model_name="kidneydiseaseprediction",
            name="user",
        ),
        migrations.RemoveField(
            model_name="nutritionprediction",
            name="user",
        ),
        migrations.RemoveField(
            model_name="strokeprediction",
            name="user",
        ),
        migrations.DeleteModel(
            name="Autism",
        ),
        migrations.DeleteModel(
            name="BrainTumor",
        ),
        migrations.DeleteModel(
            name="CovidPrediction",
        ),
        migrations.DeleteModel(
            name="DiabetesPrediction",
        ),
        migrations.DeleteModel(
            name="HepatitisPrediction",
        ),
        migrations.DeleteModel(
            name="KidneyDiseasePrediction",
        ),
        migrations.DeleteModel(
            name="NutritionPrediction",
        ),
        migrations.DeleteModel(
            name="StrokePrediction",
        ),
    ]
