from django.db import models
from django.contrib.auth.models import User
from django.conf import settings


class Pneumonia(models.Model):
    """
    Pneumonia
    ---------
    Stores an X-ray image uploaded by a user and the model’s predicted
    diagnosis text (e.g. 'Pneumonia detected' or 'Normal').

    Attributes:
        user (ForeignKey): Reference to the User who uploaded the X-ray.
        image (ImageField): The uploaded chest X-ray file.
        predicted_text (CharField): The diagnosis result generated by the AI model.
                                    Blank or null until prediction is run.
    """
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='pneumonia_segmentations'
    )
    image = models.ImageField(upload_to='uploads/')
    predicted_text = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f"{self.user.name}'s X-ray - Prediction: {self.predicted_text or 'Pending'}"

